### ISSUE TITLE
Feature "Chrome Testing" failed to install on Ubuntu 24.04 (noble) base image

### ISSUE THREAD

**Issue by gmacario** [kreemer/features#6]
Hello,

It looks like feature "Chrome Testing" failed to install on image "mcr.microsoft.com/devcontainers/base:noble"

Contents of `devcontainer.json`:

```json
{
  "name": "Ubuntu",
  "image": "mcr.microsoft.com/devcontainers/base:noble",
  "features": {
    "ghcr.io/devcontainers/features/azure-cli:1": {},
    "ghcr.io/devcontainers/features/docker-in-docker:2": {},
    "ghcr.io/devcontainers/features/node:1": {},
    "ghcr.io/devcontainers/features/python:1": {},
    "ghcr.io/devcontainers-extra/features/poetry:2": {},
    "ghcr.io/devcontainers-extra/features/tailscale:1": {},
    "ghcr.io/kreemer/features/chrometesting:latest": {},
    "ghcr.io/kreemer/features/chrometesting:1": {},
    "ghcr.io/devcontainers-extra/features/pandoc:1": {}
  },
  "customizations": {
    "vscode": {
      "extensions": [
        "esbenp.prettier-vscode",
        "mhutchie.git-graph",
        "ms-python.black-formatter"
      ]
    }
  }
}
```

Excerpt from Dev Container build log:

```text
...
[2024-12-29T11:18:59.804Z] 
[2024-12-29T11:18:59.851Z] [+] Building 163.1s (20/21)                                      docker:default
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 6.64kB                                     0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1  0.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [internal] load .dockerignore                                          0.0s
[2024-12-29T11:18:59.851Z]  => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:nob  0.1s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 168.08kB        0.0s
 => [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com  0.0s
 => CACHED [dev_containers_target_stage  2/12] RUN mkdir -p /tmp/dev-cont  0.0s
 => CACHED [dev_containers_feature_content_normalize 2/3] COPY --from=dev  0.0s
 => CACHED [dev_containers_feature_content_normalize 3/3] RUN chmod -R 07  0.0s
 => CACHED [dev_containers_target_stage  3/12] COPY --from=dev_containers  0.0s
 => CACHED [dev_containers_target_stage  4/12] RUN echo "_CONTAINER_USER_  0.0s
 => [dev_containers_target_stage  5/12] RUN --mount=type=bind,from=dev_c  13.3s
 => [dev_containers_target_stage  6/12] RUN --mount=type=bind,from=dev_c  28.3s
 => [dev_containers_target_stage  7/12] RUN --mount=type=bind,from=dev_c  12.7s
 => [dev_containers_target_stage  8/12] RUN --mount=type=bind,from=dev_c  24.3s
 => [dev_containers_target_stage  9/12] RUN --mount=type=bind,from=dev_c  20.2s
 => [dev_containers_target_stage 10/12] RUN --mount=type=bind,from=dev_c  59.4s
 => ERROR [dev_containers_target_stage 11/12] RUN --mount=type=bind,from=  4.1s
------
 > [dev_containers_target_stage 11/12] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=chrometesting_6,target=/tmp/build-features-src/chrometesting_6     cp -ar /tmp/build-features-src/chrometesting_6 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/chrometesting_6  && cd /tmp/dev-container-features/chrometesting_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/chrometesting_6:
0.170 ===========================================================================
0.170 Feature       : Chrome Testing
0.170 Description   : 
0.170 Id            : ghcr.io/kreemer/features/chrometesting
0.170 Version       : 1.0.0
0.170 Documentation : https://github.com/kreemer/features/tree/main/src/chrometesting
0.170 Options       :
0.170     VERSION="Stable"
0.170 ===========================================================================
0.180 find: '/var/lib/apt/lists/*': No such file or directory
0.180 Running apt-get update...
[2024-12-29T11:18:59.851Z] 0.299 Get:1 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
[2024-12-29T11:18:59.851Z] 0.307 Get:2 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]
0.317 Get:3 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
0.353 Get:4 https://packages.microsoft.com/repos/azure-cli noble InRelease [3564 B]
0.390 Get:5 https://dl.yarnpkg.com/debian stable/main all Packages [11.8 kB]
0.416 Get:6 https://dl.yarnpkg.com/debian stable/main amd64 Packages [11.8 kB]
0.473 Get:7 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
0.506 Get:8 https://packages.microsoft.com/repos/microsoft-ubuntu-noble-prod noble InRelease [3600 B]
0.514 Get:9 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
0.514 Get:10 https://packages.microsoft.com/repos/azure-cli noble/main amd64 Packages [878 B]
0.515 Get:11 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [707 kB]
0.580 Get:12 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.3 MB]
0.638 Get:13 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [1028 kB]
0.667 Get:14 https://pkgs.tailscale.com/stable/ubuntu noble InRelease
0.668 Get:15 https://packages.microsoft.com/repos/microsoft-ubuntu-noble-prod noble/main amd64 Packages [15.8 kB]
0.675 Get:16 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [719 kB]
0.676 Get:17 https://packages.microsoft.com/repos/microsoft-ubuntu-noble-prod noble/main all Packages [576 B]
0.695 Get:18 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Packages [15.3 kB]
0.854 Get:19 https://pkgs.tailscale.com/stable/ubuntu noble/main amd64 Packages [12.3 kB]
0.946 Get:20 https://pkgs.tailscale.com/stable/ubuntu noble/main all Packages [354 B]
1.002 Get:21 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1808 kB]
1.028 Get:22 http://archive.ubuntu.com/ubuntu noble/multiverse amd64 Packages [331 kB]
1.032 Get:23 http://archive.ubuntu.com/ubuntu noble/restricted amd64 Packages [117 kB]
1.033 Get:24 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [1254 kB]
1.043 Get:25 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [968 kB]
1.049 Get:26 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Packages [19.7 kB]
1.049 Get:27 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [724 kB]
1.053 Get:28 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [11.9 kB]
1.978 Fetched 27.7 MB in 2s (15.7 MB/s)
1.978 Reading package lists...
2.877 Reading package lists...
3.729 Building dependency tree...
3.957 Reading state information...
3.989 Package libasound2 is a virtual package provided by:
3.989   liboss4-salsa-asound2 4.2-build2020-1ubuntu3
3.989   libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
3.989 
3.993 E: Unable to locate package libgconf-2-4
3.993 E: Package 'libasound2' has no installation candidate
3.993 E: Unable to locate package gconf-service
3.993 E: Unable to locate package libappindicator1
3.995 ERROR: Feature "Chrome Testing" (ghcr.io/kreemer/features/chrometesting) failed to install! Look at the documentation at https://github.com/kreemer/features/tree/main/src/chrometesting for help troubleshooting this error.
------
[2024-12-29T11:18:59.852Z] Dockerfile.extended:83
--------------------
  82 |     
  83 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=chrometesting_6,target=/tmp/build-features-src/chrometesting_6 \
  84 | >>>     cp -ar /tmp/build-features-src/chrometesting_6 /tmp/dev-container-features \
[2024-12-29T11:18:59.852Z]   85 | >>>  && chmod -R 0755 /tmp/dev-container-features/chrometesting_6 \
  86 | >>>  && cd /tmp/dev-container-features/chrometesting_6 \
  87 | >>>  && chmod +x ./devcontainer-features-install.sh \
  88 | >>>  && ./devcontainer-features-install.sh \
  89 | >>>  && rm -rf /tmp/dev-container-features/chrometesting_6
  90 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/chrometesting_6 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/chrometesting_6  && cd /tmp/dev-container-features/chrometesting_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/chrometesting_6" did not complete successfully: exit code: 100
[2024-12-29T11:18:59.858Z] Stop (163257 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-gmacario/container-features/0.72.0-1735470969512 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:noble --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-gmacario/container-features/0.72.0-1735470969512/Dockerfile.extended -t vsc-zpat-c483050c5018acebf740e029b33391f0176fa28f79e1d008c5ce9c4477544f1b-features /home/gmacario/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-12-29T11:18:59.864Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-gmacario/container-features/0.72.0-1735470969512 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:noble --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-gmacario/container-features/0.72.0-1735470969512/Dockerfile.extended -t vsc-zpat-c483050c5018acebf740e029b33391f0176fa28f79e1d008c5ce9c4477544f1b-features /home/gmacario/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-12-29T11:18:59.864Z]     at ytA (/home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:465:1260)
[2024-12-29T11:18:59.865Z]     at bH (/home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:465:1002)
[2024-12-29T11:18:59.865Z]     at async TtA (/home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:482:3848)
[2024-12-29T11:18:59.865Z]     at async iB (/home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:482:4963)
[2024-12-29T11:18:59.865Z]     at async wrA (/home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:663:203)
[2024-12-29T11:18:59.865Z]     at async DrA (/home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:662:14830)
[2024-12-29T11:18:59.865Z]     at async /home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:482:1190
[2024-12-29T11:18:59.874Z] Stop (171111 ms): Run: /snap/code/179/usr/share/code/code /home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/gmacario/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-aa2bf141-f7ec-4b31-addb-c506439896851735470967572 --workspace-folder /home/gmacario/github/SOLARMA/zpat --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/home/gmacario/github/SOLARMA/zpat --id-label devcontainer.config_file=/home/gmacario/github/SOLARMA/zpat/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/gmacario/github/SOLARMA/zpat/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1001/wayland-0,target=/tmp/vscode-wayland-8b9336cc-a476-429a-9736-15a7b6b9d22a.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-12-29T11:18:59.874Z] Exit code 1
[2024-12-29T11:18:59.909Z] Command failed: /snap/code/179/usr/share/code/code /home/gmacario/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/gmacario/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-aa2bf141-f7ec-4b31-addb-c506439896851735470967572 --workspace-folder /home/gmacario/github/SOLARMA/zpat --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/home/gmacario/github/SOLARMA/zpat --id-label devcontainer.config_file=/home/gmacario/github/SOLARMA/zpat/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/gmacario/github/SOLARMA/zpat/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1001/wayland-0,target=/tmp/vscode-wayland-8b9336cc-a476-429a-9736-15a7b6b9d22a.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-12-29T11:18:59.909Z] Exit code 1
```

Thank you in advance for any suggestions!

**Comment by kreemer** [comment]
Hi there

Thank you for the created issue. I'll look into it, but it seems that with ubuntu 24 the list of the required dependencies has changed.

The easiest solution would be to execute the install script in the base image (without the feature) without the libasound dependency and check if chrome can be started without it.

I'm on vacation the next several weeks and check it myself afterwards.

**Comment by ignacio-decastroperez-alight** [comment]
This issue is still occurring because you have not published the changes to ghcr.io. The [package](https://github.com/kreemer/features/pkgs/container/features%2Fchrometesting ) still shows as published over a year ago but your fixes are from around 3 months ago. I can replicate the issue locally using the original code you published but the latest (unpublished) version works just fine locally

**Comment by kreemer** [comment]
Hi @ignacio-decastroperez-alight 

I have forgotten to release a new version of the feature. Now the version 1.0.1 of chrometesting should contain the new code

Can you test if it works?
Thanks!

**Comment by ignacio-decastroperez-alight** [comment]
Thank you for the quick turnaround, @kreemer. It is working now.
